default: &default
  adapter: postgresql
  encoding: utf8
  pool: 20
  reconnect: true
  reaping_frequency: 10
  timeout: 5000

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 20

deployment:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 20

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 20

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 20
